# Generated by Django 5.1.1 on 2024-09-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='modalidade',
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
