# Generated by Django 5.1.1 on 2024-09-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_match_modalidade_alter_modalidade_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidade',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
