# Generated by Django 5.1.1 on 2024-09-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_match_id_alter_modalidade_id_alter_player_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modalidade',
            new_name='Modality',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='modalidade',
            new_name='modality',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='modalidade',
            new_name='modality',
        ),
    ]
