# Generated by Django 5.1.1 on 2024-09-23 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_modalidade_modality_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
        migrations.AlterModelOptions(
            name='modality',
            options={'verbose_name': 'Modalidade', 'verbose_name_plural': 'Modalidades'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Jogador', 'verbose_name_plural': 'Jogadores'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Time', 'verbose_name_plural': 'Times'},
        ),
        migrations.AlterField(
            model_name='match',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='match',
            name='modality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.modality', verbose_name='Modality'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_a',
            field=models.IntegerField(default=0, verbose_name='Score A'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_b',
            field=models.IntegerField(default=0, verbose_name='Score B'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='core.team', verbose_name='Team A'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='core.team', verbose_name='Team B'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='core.team', verbose_name='Winner'),
        ),
        migrations.AlterField(
            model_name='modality',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='modality',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_leader',
            field=models.BooleanField(default=False, verbose_name='Is leader'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.player', verbose_name='Leader'),
        ),
        migrations.AlterField(
            model_name='team',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modality', verbose_name='Modality'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
